controller_list:
  - name: fake_right_arm_controller
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_right_2f85_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: right_arm
    pose: right_home